### ISSUE TITLE
Space char. in DeepVariant command causes DeepVariant to fail

### ISSUE THREAD

**Issue by GuillaumeHolley** [mobinasri/flagger#2]
Hi,

Just FYI, the space character in
```
--make_examples_extra_args="keep_supplementary_alignments=true, min_mapping_quality=0"
```
of the DeepVariant command (Section 3 of README) will cause DeepVariant 1.4.0 to complain about positional arguments not being allowed and stop there.
The correct argument is:
```
--make_examples_extra_args="keep_supplementary_alignments=true,min_mapping_quality=0"
```

Thanks for the tools
Guillaume

**Comment by GuillaumeHolley** [comment]
I am also wondering why using `keep_supplementary_alignments=true` if the input is the Secphase-corrected BAM which has no primary alignments (given that `--primaryOnly` seems to be the recommended practice for Secphase)?

**Comment by mobinasri** [comment]
@GuillaumeHolley Thank you so much for your useful notes

I have corrected the space typo in README noting that this space is not present in the [related wdl file](https://github.com/mobinasri/flagger/blob/613eedf99d839524ee710acf35e4b846b6bea1ab/wdls/tasks/variant_calling/deep_variant.wdl#L81)

Regarding the `--primaryOnly` parameter I meant [excluding secondary alignments](https://github.com/mobinasri/secphase/blob/450f41573918965061b7fc094de976ee47bbb7ed/programs/src/correct_bam.c#L104) with the bit-wise flag of 256. Maybe it's better to change it to `--excludeSecondary` to avoid misunderstanding in the future releases.

-Mobin

**Comment by GuillaumeHolley** [comment]
Thanks for the feedback @mobinasri, it is very useful. I will keep the  `keep_supplementary_alignments=true` then :)
