### ISSUE TITLE
flagger parameters with updated nanopore flow cell

### ISSUE THREAD

**Issue by DustinSokolowski** [mobinasri/flagger#31]
Hello,

Thank you for the excellent tool. I am interested in running flagger locally on a _de novo_ assembly that used PB hifi and ONT reads (R10.4 flowcell). Do you know if I should keep the ONT-related cutoffs as suggested on your github (which I think refer to the R9.4 accuracy) or change parameters to be a bit more stringent. For example with  FlaggerEndToEnd.maxReadDivergence [0.02 for HiFi, 0.09 for ONT, _0.06 for ONT/R10_]

Best,
Dustin

**Comment by mobinasri** [comment]
@DustinSokolowski Thanks for using Flagger and reporting your concern. This parameter is mainly used for filtering problematic reads and alignments. I don't have a exact number for R10 but one can take a brief look at alignments and see if the threshold is stringent or not (or by looking at the histogram of divergences in the bam file 'de:f:' tag). With the accuracy improvement in R10 vs R9 0.06 might be a reasonable value. If you lost a lot of alignments that means it should be higher than that. In later versions I might add a automatic mode so there will be no need to pass this value manually.

**Comment by DustinSokolowski** [comment]
Great. I'll give it a test and let you know if anything interesting comes up.
