### ISSUE TITLE
Could I use Flgger to evaluate the chromosome-level genome assembly

### ISSUE THREAD

**Issue by YutingSheep** [mobinasri/flagger#36]
Hi,

Thank you for your softwore.
I am writing to inquire whether I can use Flogger to evaluate a chromosome-level genome assembly instead of a draft dual assembly for presenting my genome evaluation results.
I have compared the chromosome-level genome assembly with the draft dual assembly, and the results are quite similar.
Thank you for your assistance.

Best Regards,
Yuting

**Comment by mobinasri** [comment]
Hi @YutingSheep Yes you can use Flagger for evaluating a chromosome-level assembly as long as your assemblies are phased since for Flagger you have to map all reads to all haplotypes (for human two haplotypes).

**Comment by YutingSheep** [comment]
OK, Thank you and good luck with your project!
