### ISSUE TITLE
end to end wdl run requires more parameters than specified in readme

### ISSUE THREAD

**Issue by Dmitry-Antipov** [mobinasri/flagger#40]
Hi 
I was trying to run hmm_flagger_end_to_end_with_mapping.wdl the way described in readme.
>After modifying inputs.json, setting mandatory parameters: sampleName, suffixForFlagger, suffixForMapping, hap1AssemblyFasta, hap2AssemblyFasta, readFiles, presetForMapping and removing unspecified parameters (they will be set to default values), users can run the command below:

However pipeline failed requiring non-listed alphaTsv paramater:
Required workflow input 'HMMFlaggerEndToEndWithMapping.alphaTsv' not specified

How should I specify this file?
There's alpha_optimum_trunc_exp_gaussian_w_4000_n_50.tsv in flagger repo - is it just a test file or real parameters file that should be used by default?

**Comment by mobinasri** [comment]
Hi @Dmitry-Antipov  Thanks for pointing this. Please use this file https://raw.githubusercontent.com/mobinasri/flagger/main/programs/config/alpha_optimum_trunc_exp_gaussian_w_4000_n_50.tsv
I added this to README as well.

**Comment by Dmitry-Antipov** [comment]
Thank you for the clarification!
