### ISSUE TITLE
Algorithm change?

### ISSUE THREAD

**Issue by jwertz01** [mobinasri/flagger#42]
Hi, do you have any validation results for the algorithm switch to HMM? Could you describe what differences in results we should expect as compared to previous versions?

Thanks,

Julie

**Comment by mobinasri** [comment]
Hi @jwertz01  Here is some preliminary results of comparing Flagger v0.4 (non-HMM) and Flagger v1.0 (HMM). As you can see the precision and recall rate of detecting different types of misassemblies have increased by varying degrees (The major one is for detecting false duplications). This is just a preliminary result of validating Flagger on some simulated misassemblies.
![Screenshot from 2024-10-22 21-51-49](https://github.com/user-attachments/assets/e2aeb68b-0d19-4015-bf96-3a4867f33d81)

**Comment by jwertz01** [comment]
Makes sense, thank you!
